# Generated by Django 5.2.16 on 2026-08-03 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cis', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order within the term.')),
                ('opens_on', models.DateField(help_text='Grades may be entered on and after this date.')),
                ('due_on', models.DateField(help_text='Grades may be entered until this date.')),
                ('is_final', models.BooleanField(default=False, help_text='The final grade collection. Writes to the registration grade that is exported to the SIS. At most one per term.')),
                ('reminder_frequency_days', models.PositiveIntegerField(default=0, help_text='How often to re-notify instructors who have not submitted. 0 disables reminders for this period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_periods', to='cis.term')),
            ],
            options={
                'ordering': ['term', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PeriodGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='grades.gradingperiod')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_grades', to='cis.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPeriodStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('', 'N/A'), ('saved', 'Grades Saved Only'), ('submitted', 'Grades Successfully Submitted')], default='', max_length=30)),
                ('status_changed_on', models.JSONField(blank=True, default=dict)),
                ('last_notified_on', models.DateField(blank=True, help_text='Drives reminder cadence; see reminder_frequency_days.', null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_statuses', to='cis.classsection')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_statuses', to='grades.gradingperiod')),
            ],
            options={
                'verbose_name_plural': 'Section period statuses',
            },
        ),
        migrations.AddConstraint(
            model_name='gradingperiod',
            constraint=models.UniqueConstraint(fields=('term', 'name'), name='grades_gradingperiod_unique_name_per_term'),
        ),
        migrations.AddConstraint(
            model_name='gradingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('term',), name='grades_gradingperiod_one_final_per_term'),
        ),
        migrations.AddConstraint(
            model_name='periodgrade',
            constraint=models.UniqueConstraint(fields=('period', 'registration'), name='grades_periodgrade_unique_per_registration'),
        ),
        migrations.AddConstraint(
            model_name='sectionperiodstatus',
            constraint=models.UniqueConstraint(fields=('period', 'class_section'), name='grades_sectionperiodstatus_unique_per_section'),
        ),
    ]
