# Generated by Django 5.2.17 on 2026-10-01 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '__first__'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSISSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('needs_mirroring', 'Needs Mirroring')], db_index=True, max_length=20)),
                ('sent_grade', models.CharField(blank=True, default='', max_length=30)),
                ('sis_record_id', models.UUIDField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('grade_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_sis_sync', to='cis.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSISSyncAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField()),
                ('grade', models.CharField(blank=True, default='', max_length=30)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True, default='')),
                ('log_url', models.CharField(blank=True, default='', max_length=500)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='grades.gradesissync')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
